general:
  kafka-topic: trader-updates
  incentive-api-url: "http://localhost:8080/incentive"

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: midas
      properties:
        spring:
          json:
            trusted:
              packages: "*"

server:
  port: 33400